# --- Base build stage ---
FROM node:20-alpine AS base
RUN npm install -g pnpm
WORKDIR /app
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY nx.json ./
RUN pnpm install --frozen-lockfile

# --- Builder stage ---
FROM base AS builder
COPY . .
RUN npx nx build web --skip-nx-cache

# -- Production runtime stage ---
FROM node:20-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist/apps/web ./web
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod
CMD [ "node", "web/server.js" ]

# --- Development stage ---
FROM base AS dev
WORKDIR /workspace
RUN ln -s /app/node_modules /workspace/node_modules
CMD [ "pnpm", "nx", "serve", "web", "--host=0.0.0.0", "--port=3000" ]