# --- Base build stage ---
FROM node:slim AS base
WORKDIR /app
ENV CI=true
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile
COPY libs/db-client/package.json libs/db-client/
COPY apps/web/package.json apps/web/
RUN pnpm install --frozen-lockfile --recursive

# --- Builder stage ---
FROM base AS builder
COPY . .
RUN npx nx build web --skip-nx-cache=false

# -- Production runtime stage ---
FROM node:slim AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist/apps/web ./web
COPY pnpm-lock.yaml package.json ./
RUN npm i -g pnpm && pnpm install --frozen-lockfile
WORKDIR /app/web
EXPOSE 3000
ENTRYPOINT [ "pnpm", "exec", "next", "start" ]

# --- Development stage ---
FROM base AS dev
WORKDIR /workspace
RUN ln -s /app/node_modules /workspace/node_modules
CMD [ "pnpm", "nx", "serve", "web", "--host=0.0.0.0", "--port=3000" ]