# --- Base build stage ---
FROM node:20-alpine AS base
RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json ./
RUN pnpm install --frozen-lockfile
COPY libs/db-client/package.json libs/db-client/
COPY apps/web/package.json apps/web/

# --- Builder stage ---
FROM base AS builder
COPY . .
RUN npx nx build web --skip-nx-cache

# -- Production runtime stage ---
FROM node:20-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist/apps/web ./web
COPY pnpm-lock.yaml package.json ./
RUN npm i -g pnpm && pnpm install --frozen-lockfile --prod
EXPOSE 3000
CMD [ "node", "web/server.js" ]

# --- Development stage ---
FROM base AS dev
WORKDIR /workspace
RUN ln -s /app/node_modules /workspace/node_modules
CMD [ "pnpm", "nx", "serve", "web", "--host=0.0.0.0", "--port=3000" ]