import { ThemeProvider } from '@/components/providers/theme-provider';
import './globals.css';
import { BetterAuthProvider } from '@/components/providers/AuthProvider';

export const metadata = {
  title: 'Temar',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className="h-full">
        <BetterAuthProvider>
          <ThemeProvider attribute="class" disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </BetterAuthProvider>
      </body>
    </html>
  );
}
