import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  paragraph: 'mb-2 leading-relaxed',
  heading: {
    h1: 'text-3xl font-bold mt-6 mb-3',
    h2: 'text-2xl font-semibold mt-5 mb-2',
    h3: 'text-xl font-semibold mt-4 mb-2',
    h4: 'text-lg font-semibold mt-3 mb-1',
    h5: 'text-base font-semibold mt-2 mb-1',
    h6: 'text-sm font-semibold mt-2 mb-1',
  },
  quote: 'border-l-4 border-muted-foreground/30 pl-4 italic text-muted-foreground my-2',
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal ml-6 mb-2',
    ul: 'list-disc ml-6 mb-2',
    listitem: 'mb-1',
    listitemChecked: 'line-through text-muted-foreground',
    listitemUnchecked: '',
  },
  link: 'text-primary underline cursor-pointer',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-muted px-1.5 py-0.5 rounded text-sm font-mono',
    highlight: 'bg-yellow-200 dark:bg-yellow-800',
  },
  code: 'bg-muted/50 block rounded-md p-3 overflow-auto font-mono text-sm my-2',
  codeHighlight: {
    atrule: 'text-blue-500',
    attr: 'text-blue-500',
    boolean: 'text-purple-500',
    builtin: 'text-cyan-500',
    cdata: 'text-gray-500',
    char: 'text-green-500',
    class: 'text-yellow-500',
    'class-name': 'text-yellow-500',
    comment: 'text-gray-500 italic',
    constant: 'text-purple-500',
    deleted: 'text-red-500',
    doctype: 'text-gray-500',
    entity: 'text-orange-500',
    function: 'text-blue-400',
    important: 'text-orange-500 font-bold',
    inserted: 'text-green-500',
    keyword: 'text-purple-500',
    namespace: 'text-gray-500',
    number: 'text-orange-500',
    operator: 'text-gray-400',
    prolog: 'text-gray-500',
    property: 'text-blue-500',
    punctuation: 'text-gray-400',
    regex: 'text-green-500',
    selector: 'text-green-500',
    string: 'text-green-500',
    symbol: 'text-purple-500',
    tag: 'text-red-500',
    url: 'text-blue-500 underline',
    variable: 'text-orange-500',
  },
  horizontalRule: 'my-4 border-t border-border',
};

export default theme;
